config/routes.rb
Rails.application.routes.draw do
  root 'core#index'
  resources :patterns
  resources :reports
  resources :core
  resource  :application
  resources :stations

end

app/models/datasource.rb
class Datasource < ActiveRecord::Base
  belongs_to :sourcetype
  belongs_to :pattern
  has_many :reports
end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  has_one :datasource
end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :reports

  def to_s
    "#{Time.at(self.datetime)}"
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :station
  belongs_to :datasource
  belongs_to :period
end

app/models/sourcetype.rb
class Sourcetype < ActiveRecord::Base
  has_many :datasources
end

app/models/station.rb
class Station < ActiveRecord::Base
  has_many :reports

  def to_s
    "#{self.name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/core_controller.rb
require 'nokogiri'
require 'open-uri'
require 'json'

class CoreController < ApplicationController
  def index
    @reports = Report.all
    @periods = Period.all
    respond_to do |format|
      format.html { render :template => "core/home" }
    end
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]

  # GET /patterns
  # GET /patterns.json
  def index
    @patterns = Pattern.all
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Pattern was successfully created.' }
        format.json { render :show, status: :created, location: @pattern }
      else
        format.html { render :new }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { render :show, status: :ok, location: @pattern }
      else
        format.html { render :edit }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url, notice: 'Pattern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:station_name, :time, :temperature, :rainfall, :dew_point, :wind_direction, :wind_speed)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to root_path, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to root_path, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:time, :temperature, :rainfall, :dew_point, :wind_direction, :wind_speed, :station_id)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :longitude, :latitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/core/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :station %><br>
      <%= f.collection_select :station_id,Station.all,:id,:name %>
    </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :dew_point %><br>
    <%= f.text_field :dew_point %>
  </div>
  <div class="field">
    <%= f.label :wind_direction %><br>
    <%= f.text_field :wind_direction %>
  </div>
  <div class="field">
    <%= f.label :wind_speed %><br>
    <%= f.text_field :wind_speed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/core/home.erb
<p id="notice"><%= notice %></p>

<h1>BOM Weather Reports</h1>

<table class="table">
  <thead>
  <tr>
    <th>Station</th>
    <th>Source</th>
    <th>Time</th>
    <th>Temperature</th>
    <th>Rainfall</th>
    <th>Dew point</th>
    <th>Wind direction</th>
    <th>Wind speed</th>
  </tr>
  </thead>

  <tbody>
  <% @periods.last.reports.each do |report| %>
      <tr>
        <td><%= report.station %></td>
        <td><%= report.datasource.name %></td>
        <td><%= report.time %></td>
        <td><%= report.temperature %></td>
        <td><%= report.rainfall %></td>
        <td><%= report.dew_point %></td>
        <td><%= report.wind_direction %></td>
        <td><%= report.wind_speed %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather Page</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <div class="container">
      <%= link_to "weather", reports_path, class: 'navbar-brand'%>
    </div>
  </div>
</div>
<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/patterns/_form.html.erb
<%= form_for(@pattern) do |f| %>
    <% if @pattern.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

          <ul>
            <% @pattern.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :station_name %><br>
      <%= f.text_field :station_name %>
    </div>
    <div class="field">
      <%= f.label :time %><br>
      <%= f.text_field :time %>
    </div>
    <div class="field">
      <%= f.label :temperature %><br>
      <%= f.text_field :temperature %>
    </div>
    <div class="field">
      <%= f.label :rainfall %><br>
      <%= f.text_field :rainfall %>
    </div>
    <div class="field">
      <%= f.label :dew_point %><br>
      <%= f.text_field :dew_point %>
    </div>
    <div class="field">
      <%= f.label :wind_direction %><br>
      <%= f.text_field :wind_direction %>
    </div>
    <div class="field">
      <%= f.label :wind_speed %><br>
      <%= f.text_field :wind_speed %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/patterns/edit.html.erb
<h1>Editing Pattern</h1>

<%= render 'form' %>

<%= link_to 'Show', @pattern %> |
<%= link_to 'Back', patterns_path %>

app/views/patterns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patterns</h1>

<table>
  <thead>
    <tr>
      <th>Station name</th>
      <th>Time</th>
      <th>Temperature</th>
      <th>Dew point</th>
      <th>Wind direction</th>
      <th>Wind speed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patterns.each do |pattern| %>
      <tr>
        <td><%= pattern.station_name %></td>
        <td><%= pattern.time %></td>
        <td><%= pattern.temperature %></td>
        <td><%= pattern.dew_point %></td>
        <td><%= pattern.wind_direction %></td>
        <td><%= pattern.wind_speed %></td>
        <td><%= link_to 'Show', pattern %></td>
        <td><%= link_to 'Edit', edit_pattern_path(pattern) %></td>
        <td><%= link_to 'Destroy', pattern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pattern', new_pattern_path %>

app/views/patterns/new.html.erb
<h1>New Pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', patterns_path %>

app/views/patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station name:</strong>
  <%= @pattern.station_name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @pattern.time %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @pattern.temperature %>
</p>

<p>
  <strong>Dew point:</strong>
  <%= @pattern.dew_point %>
</p>

<p>
  <strong>Wind direction:</strong>
  <%= @pattern.wind_direction %>
</p>

<p>
  <strong>Wind speed:</strong>
  <%= @pattern.wind_speed %>
</p>

<%= link_to 'Edit', edit_pattern_path(@pattern) %> |
<%= link_to 'Back', patterns_path %>

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
    <% if @report.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

          <ul>
            <% @report.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :station %><br>
      <%= f.collection_select :station_id, Station.all, :id, :name %>
    </div>
    <div class="field">
      <%= f.label :time %><br>
      <%= f.datetime_select :time %>
    </div>
    <div class="field">
      <%= f.label :temperature %><br>
      <%= f.text_field :temperature %>
    </div>
    <div class="field">
      <%= f.label :rainfall %><br>
      <%= f.text_field :rainfall %>
    </div>
    <div class="field">
      <%= f.label :dew_point %><br>
      <%= f.text_field :dew_point %>
    </div>
    <div class="field">
      <%= f.label :wind_direction %><br>
      <%= f.text_field :wind_direction %>
    </div>
    <div class="field">
      <%= f.label :wind_speed %><br>
      <%= f.text_field :wind_speed %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<table class="table">
  <thead>
    <tr>
      <th>Time</th>
      <th>Temperature</th>
      <th>Dew point</th>
      <th>Wind direction</th>
      <th>Wind speed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.time %></td>
        <td><%= report.temperature %></td>
        <td><%= report.dew_point %></td>
        <td><%= report.wind_direction %></td>
        <td><%= report.wind_speed %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @report.time %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @report.temperature %>
</p>

<p>
  <strong>Dew point:</strong>
  <%= @report.dew_point %>
</p>

<p>
  <strong>Wind direction:</strong>
  <%= @report.wind_direction %>
</p>

<p>
  <strong>Wind speed:</strong>
  <%= @report.wind_speed %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.longitude %></td>
        <td><%= station.latitude %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @station.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @station.latitude %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>